# Generated by Django 5.1.2 on 2024-12-01 21:32

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Classement',
            fields=[
                ('niveau', models.IntegerField(primary_key=True, serialize=False)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sexe',
            fields=[
                ('sexe', models.CharField(max_length=50, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Sports',
            fields=[
                ('sport_type', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Terrain',
            fields=[
                ('numero_terrain', models.IntegerField(primary_key=True, serialize=False)),
                ('commentaire', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('type', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='GroupPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True)),
                ('role', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='auth.group')),
            ],
        ),
        migrations.CreateModel(
            name='Tournoi',
            fields=[
                ('idtournoi', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=50)),
                ('periode_debut', models.DateField(default=datetime.date.today)),
                ('periode_fin', models.DateField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('terrains', models.ManyToManyField(blank=True, null=True, to='gui.terrain')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gui.type')),
            ],
        ),
        migrations.CreateModel(
            name='MatchDeTournoi',
            fields=[
                ('id_match', models.AutoField(primary_key=True, serialize=False)),
                ('score', models.CharField(blank=True, default='a', max_length=50, null=True)),
                ('points', models.IntegerField(blank=True, default=0, null=True)),
                ('date_heure_match', models.DateTimeField()),
                ('description', models.TextField(blank=True, null=True)),
                ('tournoi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gui.tournoi')),
            ],
        ),
        migrations.CreateModel(
            name='Equipe',
            fields=[
                ('nom_equipe', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('tournoi', models.ManyToManyField(blank=True, null=True, to='gui.tournoi')),
            ],
        ),
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipe', models.ManyToManyField(blank=True, to='gui.equipe')),
                ('match', models.ManyToManyField(blank=True, to='gui.matchdetournoi')),
                ('niveau', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gui.classement')),
                ('sexe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gui.sexe')),
                ('sport_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gui.sports')),
                ('tournoi', models.ManyToManyField(blank=True, to='gui.tournoi')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
